spring:
  main:
    web-application-type: reactive
  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /graphql

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
            user-name-attribute: username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
logging:
  level:
    web: debug


